services:
  - type: web
    name: upm-universal-patient-monitoring
    runtime: node
    plan: free

    buildCommand: npm install
    startCommand: npm start

    envVars:
      - key: NODE_ENV
        value: production

    autoDeploy: true