services:
  - type: web
    name: upm-universal-patient-monitoring
    runtime: node
    plan: free

    buildCommand: npm install
    startCommand: npm start

    autoDeploy: true

    envVars:
      - key: NODE_ENV
        value: production

      - key: MONGODB_URI
        sync: false

      - key: JWT_SECRET
        sync: false